name: "Auto-fix Linting Issues"
description: "Automatically fix linting, formatting, and documentation issues before running tests"
author: "NUAA Project"

runs:
  using: "composite"
  steps:
    - name: Auto-fix all linting and formatting issues
      shell: bash
      run: |
        echo "ðŸ”§ Auto-fixing linting issues (REQUIRED before any tests)..."
        echo ""
        
        # Run Black formatter
        echo "â–¶ï¸ Running Black formatter..."
        black src/nuaa_cli tests scripts/python 2>&1 || true
        echo "âœ… Black complete"
        echo ""
        
        # Run Ruff with auto-fix
        echo "â–¶ï¸ Running Ruff auto-fix..."
        ruff check --fix src/nuaa_cli tests scripts/python 2>&1 || true
        echo "âœ… Ruff complete"
        echo ""
        
        # Run pre-commit hooks (includes trailing whitespace, EOF, YAML/TOML checks)
        echo "â–¶ï¸ Running pre-commit hooks..."
        pre-commit run --all-files 2>&1 || true
        echo "âœ… Pre-commit complete"
        echo ""
        
        # Update agent documentation
        echo "â–¶ï¸ Updating agent documentation..."
        python scripts/python/update_agents_docs.py 2>&1 || true
        echo "âœ… Agent docs updated"
        echo ""
        
        echo "âœ… All auto-fixes applied successfully!"
        echo ""
        echo "ðŸ“Š Changes summary:"
        if git diff --quiet; then
          echo "  No changes were needed - code is already clean! ðŸŽ‰"
        else
          echo "  The following files were auto-fixed:"
          git --no-pager diff --stat --color=always || true
        fi
